dictionnaire = {'Alger Algerie flag architecture.jpg': ('alger', 'algerie', 'flag', 'architecture'),
                'Elizabeth Tower clock architecture trees.jpg': ('elizabeth', 'tower' ,'clock', 'architecture', 'trees'),
                'alger flag mosque architecture.jpg': ('alger', 'flag', 'mosque', 'architecture'),
                'apple.jpg': ('apple',),
                'Aston Martin car green vehicle.jpg': ('aston', 'martin', 'car', 'green', 'vehicle'),
                'blue car vehicle bmw luxury.jpg': ('blue', 'car', 'vehicle', 'bmw', 'luxury'),
                'BUGATTI chiron blue car vehicle.jpg': ('bugatti', 'chiron', 'blue', 'car', 'vehicle'),
                'BUGATTI Divo paris blue eiffel tower car vehicle.jpg': ('bugatti', 'divo', 'paris', 'blue', 'eiffel', 'tower', 'car', 'vehicle'),
                'BUGATTI Divo white car vehicle.jpg': ('bugatti', 'divo', 'white', 'car', 'vehicle'),
                'car electric white charger sign vehicle.jpg': ('car', 'electric', 'white', 'charger', 'sign', 'vehicle'),
                'car red track vehicle.jpg': ('car', 'red', 'track', 'vehicle'),
                'cow boat sea .jpg': ('cow', 'boat', 'sea'),
                'cow sea boat.jpg': ('cow', 'boat', 'sea'),
                'dodge ram truck trucks white vehicle.jpg': ('dodge', 'ram', 'truck', 'trucks', 'white', 'vehicle'),
                'fruit apple red yellow.jpg': ('fruit', 'apple', 'red', 'yellow'),
                'grandphare jijel sea nature.jpg': ('grandphare', 'jijel', 'sea', 'nature'),
                'green bmw car vehicle luxury.jpg': ('green', 'bmw', 'car', 'vehicle', 'luxury'),
                'lamborghini white black vehicle.jpg': ('lamborghini', 'white', 'black', 'vehicle'),
                'Landscape trees water.jpg': ('landscape', 'trees', 'water'),
                'laptop apple macbook thinkpad microsoft.jpg': ('laptop', 'apple', 'macbook', 'thinkpad', 'microsoft'),
                'mecca tower clock.jpg': ('mecca', 'tower', 'clock'),
                'mountain landscape.jpg': ('mountain', 'landscape'),
                'orange fruit.jpg': ('orange', 'fruit'),
                'Orange.jpg': ('orange',),
                'paris eiffel tower trees.jpg': ('paris', 'eiffel', 'tower', 'trees'),
                'parking cars vehicle.jpg': ('parking', 'cars', 'vehicle', 'trees'),
                'Programmer-Room-Setup-A-Complete-Guide_943688c67f9.jpg': ('programmer', 'room', 'setup'),
                'Rolls Royce Boat Tail car vehicle luxury.jpg': ('rolls', 'royce', 'boat', 'tail', 'car', 'vehicle', 'luxury'),
                'trees elhama.jpg': ('trees', 'elhama'),
                'usa flag architecture.jpg': ('usa', 'flag', 'architecture'),
                'white blue black car truck scania trees trailer vehicle.jpg': ('white', 'blue',  'black',  'car',  'truck',  'scania',  'trees',  'trailer',  'vehicle'),
                'white truck trucks vehicle.jpg': ('white', 'truck',  'trucks',  'vehicle'),
                }