dictionnaire = {
    "Alger Algerie flag architecture.jpg": {
        "flag": 0.9,
        "alger": 0.8,
        "algerie": 0.7,
        "architecture": 0.7,
    },
    "Elizabeth Tower clock architecture trees.jpg": {
        "elizabeth": 0.9,
        "tower": 0.9,
        "clock": 0.9,
        "architecture": 0.7,
        "trees": 0.5,
    },
    "alger flag mosque architecture.jpg": {
        "mosque": 0.8,
        "flag": 0.7,
        "alger": 0.9,
        "architecture": 0.6,
    },
    "apple.jpg": {"apple": 0.9},
    "Aston Martin car green vehicle.jpg": {
        "car": 0.9,
        "green": 0.9,
        "aston": 0.8,
        "vehicle": 0.8,
        "martin": 0.7,
    },
    "blue car vehicle bmw luxury.jpg": {
        "car": 0.9,
        "blue": 0.8,
        "vehicle": 0.8,
        "bmw": 0.7,
        "luxury": 0.6,
    },
    "BUGATTI chiron blue car vehicle.jpg": {
        "car": 0.9,
        "bugatti": 0.8,
        "blue": 0.8,
        "vehicle": 0.8,
        "chiron": 0.7,
    },
    "BUGATTI Divo paris blue eiffel tower car vehicle.jpg": {
        "car": 0.9,
        "bugatti": 0.8,
        "blue": 0.8,
        "vehicle": 0.8,
        "divo": 0.7,
        "eiffel": 0.7,
        "paris": 0.6,
        "tower": 0.6,
    },
    "BUGATTI Divo white car vehicle.jpg": {
        "car": 0.9,
        "bugatti": 0.8,
        "white": 0.8,
        "vehicle": 0.8,
        "divo": 0.7,
    },
    "car electric white charger sign vehicle.jpg": {
        "charger": 0.9,
        "car": 0.8,
        "electric": 0.7,
        "sign": 0.7,
        "vehicle": 0.7,
        "white": 0.6,
    },
    "car red track vehicle.jpg": {"car": 0.9, "red": 0.8, "track": 0.8, "vehicle": 0.8},
    "cow boat sea .jpg": {"cow": 0.9, "sea": 0.7, "boat": 0.6},
    "cow sea boat.jpg": {"cow": 0.9, "sea": 0.7, "boat": 0.8},
    "dodge ram truck trucks white vehicle.jpg": {
        "truck": 0.85,
        "trucks": 0.9,
        "white": 0.6,
        "vehicle": 0.8,
        "dodge": 0.6,
        "ram": 0.5,
    },
    "fruit apple red yellow.jpg": {
        "fruit": 0.9,
        "apple": 0.9,
        "red": 0.8,
        "yellow": 0.8,
    },
    "grandphare jijel sea nature.jpg": {
        "grandphare": 0.9,
        "jijel": 0.8,
        "nature": 0.8,
        "sea": 0.7,
    },
    "green bmw car vehicle luxury.jpg": {
        "green": 0.9,
        "car": 0.9,
        "vehicle": 0.8,
        "bmw": 0.7,
        "luxury": 0.6,
    },
    "lamborghini white black vehicle.jpg": {
        "lamborghini": 0.9,
        "white": 0.9,
        "vehicle": 0.9,
        "black": 0.7,
    },
    "Landscape trees water.jpg": {"landscape": 0.9, "water": 0.9, "trees": 0.8},
    "laptop apple macbook thinkpad microsoft.jpg": {
        "laptop": 0.9,
        "apple": 0.7,
        "macbook": 0.7,
        "thinkpad": 0.7,
        "microsoft": 0.7,
    },
    "mecca tower clock.jpg": {"mecca": 0.9, "tower": 0.9, "clock": 0.9},
    "mountain landscape.jpg": {"mountain": 0.9, "landscape": 0.9},
    "orange fruit.jpg": {"orange": 0.9, "fruit": 0.9},
    "Orange.jpg": {"orange": 0.9},
    "paris eiffel tower trees.jpg": {
        "eiffel": 0.9,
        "tower": 0.9,
        "paris": 0.7,
        "trees": 0.7,
    },
    "parking cars vehicle.jpg": {"parking": 0.9, "cars": 0.9, "vehicle": 0.9},
    "Programmer-Room-Setup-A-Complete-Guide_943688c67f9.jpg": {
        "setup": 0.9,
        "room": 0.8,
        "programmer": 0.7,
    },
    "Rolls Royce Boat Tail car vehicle luxury.jpg": {
        "car": 0.9,
        "rolls": 0.8,
        "vehicle": 0.8,
        "royce": 0.7,
        "luxury": 0.7,
        "boat": 0.4,
        "tail": 0.3,
    },
    "trees elhama.jpg": {"trees": 0.9, "elhama": 0.8},
    "usa flag architecture.jpg": {"flag": 0.85, "architecture": 0.9, "usa": 0.8},
    "white blue black car truck scania trees trailer vehicle.jpg": {
        "truck": 0.9,
        "trailer": 0.9,
        "scania": 0.8,
        "vehicle": 0.8,
        "white": 0.7,
        "car": 0.7,
        "blue": 0.5,
        "black": 0.4,
        "trees": 0.3,
    },
    "white truck trucks vehicle.jpg": {
        "truck": 0.9,
        "trucks": 0.9,
        "white": 0.8,
        "vehicle": 0.8,
    },
}
